const page_urls = [
    { info: "[测试]", url: "test" },
    { info: "[失智]不会吧不会吧不会吧", url: "cyberpunk/buhui" },
    { info: "[游戏]2048", url: "games/2048" },
    { info: "[游戏]鸡尾酒", url: "games/cocktail" },
    { info: "[游戏]是一扇窗捏", url: "games/window" },
    { info: "[原神]圣遗物筛选", url: "genshin/artifact" },
    { info: "[原神]方块解谜", url: "genshin/cube riddle" },
    { info: "[原神]生日动态贺图", url: "genshin/dynamic_birth_pic" },
    { info: "[原神]官网视频链接集合", url: "genshin/HD_video" },
    { info: "[英语]连词学习", url: "study/conjunction" },
    { info: "[英语]句子结构染色", url: "study/grammar" },
    { info: "[英语]单词书 v1", url: "study/words" },
    { info: "[英语]单词书 v2", url: "study/words-vue3" },
    { info: "[英语]单词书 v3", url: "study/words_v3" },
    { info: "[工具]长安中二时辰", url: "tools/time" },
    { info: "[工具]文字钟", url: "tools/word-clock" },
];
